CREATE TABLE IF NOT EXISTS `EDUCADADOS`.`FT_OFERTA_CURSO` (
        `ID` INT KEY AUTO_INCREMENT,
        `NR_ANO` INT NULL,
        `CD_IES` INT NULL,
        `CD_MUNICIPIO` INT NULL,
        `CD_CURSO` VARCHAR(80) NULL,
        `QT_OFERTA_TOTAL` INT NULL,
        `QT_INSCRITO_TOTAL` INT NULL,
        `QT_INGRESSANTE_TOTAL` INT NULL,
        `QT_MATRICULA_TOTAL` INT NULL,
        `QT_CONCLUINTE_TOTAL` INT NULL
    );
