CREATE TABLE IF NOT EXISTS `EDUCADADOS`.`DIM_IES` (
    `CD_IES` INT PRIMARY KEY,
    `NM_IES` VARCHAR(255) NOT NULL,
    `CD_MUNICIPIO` INT NULL,
    `SG_IES` VARCHAR(20) NULL,
    `CD_MANTENEDORA` INT NULL,
    `NM_MANTENEDORA` VARCHAR(255) NULL,
    `CD_ORGANIZACAO` INT NULL,
    `CD_CATEGORIA` INT NULL,
    `DS_ENDERECO` VARCHAR(255) NULL,
    `NR_ENDERECO` VARCHAR(20) NULL,
    `DS_COMPLEMENTO` VARCHAR(80) NULL,
    `DS_BAIRRO` VARCHAR(255) NULL,
    `NR_CEP` VARCHAR(8) NULL
);